### ISSUE TITLE
How to end to end test is set up to leverage this work

### ISSUE THREAD

**Issue by cactusme** [danielabar/hack-karma-https#1]
I am having trouble getting the secure cookies to be sent by karma to the remote application via the karma proxy.  Do you have any quick example to show how this is done?  Thanks.

**Comment by danielabar** [comment]
This project is pretty old, it's from the Angular 1.07 days, when end-to-end testing was done with Karma's ng-scenario runner. Since then, that's been deprecated.

Now Angular end to end testing is done more easily with [Protractor](https://github.com/angular/protractor). Give it a try and see if it solves your problem.

**Comment by cactusme** [comment]
Thanks!
